linters:
  enable:
    - dupl
    - errname
    - unconvert
    - unparam
    - sloglint
    - mirror
linters-settings:
  unused:
    field-writes-are-uses: false
    exported-fields-are-used: false
    local-variables-are-used: false
