// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/sedonn/song-library-service/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// ArtistProvider is an autogenerated mock type for the ArtistProvider type
type ArtistProvider struct {
	mock.Mock
}

// Artist provides a mock function with given fields: ctx, id
func (_m *ArtistProvider) Artist(ctx context.Context, id uint64) (models.Artist, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Artist")
	}

	var r0 models.Artist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (models.Artist, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) models.Artist); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Artist)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewArtistProvider creates a new instance of ArtistProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArtistProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArtistProvider {
	mock := &ArtistProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
