// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/sedonn/song-library-service/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// ArtistSaver is an autogenerated mock type for the ArtistSaver type
type ArtistSaver struct {
	mock.Mock
}

// SaveArtist provides a mock function with given fields: ctx, a
func (_m *ArtistSaver) SaveArtist(ctx context.Context, a models.Artist) (models.Artist, error) {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for SaveArtist")
	}

	var r0 models.Artist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Artist) (models.Artist, error)); ok {
		return rf(ctx, a)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Artist) models.Artist); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Get(0).(models.Artist)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Artist) error); ok {
		r1 = rf(ctx, a)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewArtistSaver creates a new instance of ArtistSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArtistSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArtistSaver {
	mock := &ArtistSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
