// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/sedonn/song-library-service/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// ArtistDeleter is an autogenerated mock type for the ArtistDeleter type
type ArtistDeleter struct {
	mock.Mock
}

// DeleteArtist provides a mock function with given fields: ctx, a
func (_m *ArtistDeleter) DeleteArtist(ctx context.Context, a models.Artist) (models.Artist, error) {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for DeleteArtist")
	}

	var r0 models.Artist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Artist) (models.Artist, error)); ok {
		return rf(ctx, a)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Artist) models.Artist); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Get(0).(models.Artist)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Artist) error); ok {
		r1 = rf(ctx, a)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewArtistDeleter creates a new instance of ArtistDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArtistDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArtistDeleter {
	mock := &ArtistDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
